// seed.js – Migra todos los productos de data.js a la base de datos Supabase
// Ejecutar con: node prisma/seed.js

const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const prisma = new PrismaClient();

const productos = [
  { id: 1, nombre: "Cachos Hair Jelly", marca: "SKALA (Línea Brasil)", categoria: "cabello", descripcion: "Gelatina capilar especialmente formulada para definir y realzar todo tipo de rizos. Proporciona definición, hidratación y protección térmica. Ideal para mantener los rizos con aspecto natural, sin encrespamiento y con brillo duradero. #1 en ventas en Brasil.", caracteristicas: ["1000g","Para todo tipo de rizos","Definición y protección","Gelatina capilar"], imagen: "/img/lote1/producto1.png", price: "₡8000" },
  { id: 2, nombre: "Óleo de Argan", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento nutritivo y revitalizante con aceite de argán para cabellos secos y opacos. Formulado con resistencia capilar mejorada, proporciona nutrición profunda, brillo intenso y suavidad. 100% vegano y sin ingredientes de origen animal.", caracteristicas: ["1000g","Aceite de Argán","100% Vegano","Nutrición y revitalización"], imagen: "/img/lote1/producto2.png", price: "₡5000" },
  { id: 3, nombre: "Keratina Vegetal", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento revitalizante y fortalecedor con keratina vegetal. Diseñado para reparar, fortalecer y restaurar la estructura capilar. Ideal para cabellos débiles, quebradizos o dañados por procesos químicos. Co-wash.", caracteristicas: ["1000g","Keratina Vegetal","Revitaliza y fortalece","Co-wash"], imagen: "/img/lote1/producto3.png", price: "₡5000" },
  { id: 4, nombre: "Óleo de Coco", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento nutritivo e hidratante profundo con aceite de coco. Proporciona nutrición intensiva, hidratación profunda y restauración capilar. 100% vegano, ideal para cabellos secos y dañados que necesitan recuperar vitalidad.", caracteristicas: ["1000g","Aceite de Coco","100% Vegano","Nutrición e hidratación profunda"], imagen: "/img/lote1/producto4.png", price: "₡5000" },
  { id: 5, nombre: "12 em 1", marca: "SKALA", categoria: "cabello", descripcion: "Tratamiento multibeneficio que ofrece 12 beneficios en un solo producto. Proporciona restauración, brillo, suavidad, hidratación y protección. Fórmula innovadora para cabellos renovados que combina múltiples tratamientos en una sola aplicación.", caracteristicas: ["1000g","12 beneficios","Restauración y brillo","Liberado"], imagen: "/img/lote1/producto5.png", price: "₡5000" },
  { id: 6, nombre: "Genetiqs", marca: "SKALA (Línea GENETIQS)", categoria: "cabello", descripcion: "Tratamiento profesional que proporciona fuerza, brillo e hidratación. Formulado con fuerza botánica para cabellos opacos, débiles y sin frizz. Diseñado para transformar cabellos debilitados en cabellos fuertes y radiantes.", caracteristicas: ["1000g","Fuerza botánica","Brillo e hidratación","Liberado"], imagen: "/img/lote1/producto6.png", price: "₡5000" },
  { id: 7, nombre: "Coquetel de Frutas Kids", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 especialmente formulado para cabellos infantiles. Con coco y aceite de almendras, limpia y desenreda suavemente mientras nutre el cabello de los niños. Fórmula dermatológicamente testeada, suave y divertida.", caracteristicas: ["1000g","2 en 1","Coco y almendras","Para niños","Liberado"], imagen: "/img/lote1/producto7.png", price: "₡5000" },
  { id: 8, nombre: "Bomba de Biotina", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento fortificante con biotina para cabellos débiles y quebradizos. Proporciona nutrición, fortalecimiento y crecimiento saludable del cabello. La biotina ayuda a mejorar la estructura capilar desde la raíz hasta las puntas.", caracteristicas: ["1000g","Biotina","Nutrición y fortalecimiento","Liberado"], imagen: "/img/lote1/producto8.png", price: "₡5000" },
  { id: 9, nombre: "Cacau", marca: "SKALA (Línea Brasil)", categoria: "cabello", descripcion: "Tratamiento con cacao que proporciona fuerza y brillo al cabello. Enriquecido con las propiedades antioxidantes del cacao, nutre profundamente y protege el cabello, dejándolo suave, brillante y saludable con un aroma delicioso.", caracteristicas: ["1000g","Cacao","Fuerza y brillo","Hidratación"], imagen: "/img/lote1/producto9.png", price: "₡5000" },
  { id: 10, nombre: "Divino Putinho #Influencer", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 hidratante libre de sulfatos. Crema multiuso que limpia y trata en un solo paso, ideal para mantener rizos definidos y cabello hidratado.", caracteristicas: ["1000g","2 en 1","Libre de sulfato","Hidratante","Liberado"], imagen: "/img/lote1/producto10.png", price: "₡5000" },
  { id: 11, nombre: "Creme 3em1 Glicólico", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 3 en 1 con ácido glicólico que funciona como tratamiento, súper acondicionador y crema para peinar. Con complejo 6% glicolizado que proporciona fuerza y brillo intenso. #1 en Brasil.", caracteristicas: ["1000g","3 en 1","Ácido Glicólico","6% Complejo","Liberado"], imagen: "/img/lote2/producto11.png", price: "₡5000" },
  { id: 12, nombre: "Reacionados Força e Brilho", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 de fuerza y brillo especialmente diseñado para cabellos reacionados. Con extracto mixto de açaí, aceite de coco y buriti.", caracteristicas: ["1000g","2 en 1","Açaí y Buriti","Fuerza y brillo","Liberado"], imagen: "/img/lote2/producto12.png", price: "₡5000" },
  { id: 13, nombre: "Poder Desarmante", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 con aceite de argán y control vegetal D-Pantenol que controla y desenreda el cabello.", caracteristicas: ["1000g","2 en 1","Aceite de Argán","D-Pantenol","Liberado Free","Co-wash"], imagen: "/img/lote2/producto13.png", price: "₡5000" },
  { id: 14, nombre: "Divina Cor", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 especialmente formulado para cabellos teñidos. Con proteínas de arroz, vitamina E, extracto de uva y aceite de coco.", caracteristicas: ["1000g","2 en 1","Para cabello teñido","Protección del color","Liberado"], imagen: "/img/lote2/producto14.png", price: "₡5000" },
  { id: 15, nombre: "Lama Negra Activated Charcoal", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento purificante con carbón activado que proporciona maciez y brillo. La lama negra limpia profundamente el cuero cabelludo. 100% vegano.", caracteristicas: ["1000g","Carbón Activado","Maciez y brillo","100% Vegano","Liberado Free"], imagen: "/img/lote2/producto15.png", price: "₡5000" },
  { id: 16, nombre: "Frutástica! Uva Brilho Extremo", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 con extracto de uva que proporciona brillo extremo. #1 en Brasil.", caracteristicas: ["1000g","2 en 1","Extracto de Uva","Brillo extremo","Hidratación","Liberado"], imagen: "/img/lote2/producto16.png", price: "₡5000" },
  { id: 17, nombre: "Frutástica! Morango Nutrição e Brilho", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 con extracto de fresa que proporciona nutrición y brillo. #1 en Brasil.", caracteristicas: ["1000g","2 en 1","Extracto de Fresa","Nutrición y brillo","Liberado"], imagen: "/img/lote2/producto17.png", price: "₡5000" },
  { id: 18, nombre: "Banana e Bacuri", marca: "SKALA (Línea Brasil)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 con banana y bacuri que proporciona reparación y brillo. Combina las propiedades nutritivas de la banana con el aceite de bacuri amazónico.", caracteristicas: ["1000g","2 en 1","Banana y Bacuri","Reparación y brillo","Liberado"], imagen: "/img/lote2/producto18.png", price: "₡5000" },
  { id: 19, nombre: "Maracujá e Óleo de Patauá", marca: "SKALA (Línea Brasil)", categoria: "cabello", descripcion: "Tratamiento con maracuyá y aceite de patauá amazónico. Nutre, hidrata y restaura el cabello naturalmente. #1 en Brasil.", caracteristicas: ["1000g","Maracuyá y Patauá","Nutrición tropical","Leave-in"], imagen: "/img/lote2/producto19.png", price: "₡5000" },
  { id: 20, nombre: "Dona Skala", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Tratamiento 2 en 1 con manteca de karité, pantenol, aceite de coco, queratina y ceramidas. Combinación de ingredientes premium para un tratamiento completo y efectivo.", caracteristicas: ["1000g","2 en 1","Karité y Ceramidas","Queratina y Pantenol","Liberado"], imagen: "/img/lote2/producto20.png", price: "₡5000" },
  { id: 21, nombre: "Caju e Murumuru", marca: "SKALA (Línea Brasil)", categoria: "cabello", descripcion: "Tratamiento con cajú y manteca de murumuru amazónica que proporciona resistencia y brillo.", caracteristicas: ["1000g","Cajú y Murumuru","Resistencia y brillo","Liberado"], imagen: "/img/lote2/producto21.png", price: "₡5000" },
  { id: 22, nombre: "Kit 12 em 1 - Fios Renovados", marca: "SKALA", categoria: "cabello", descripcion: "Kit precio especial que incluye shampoo 325ml y acondicionador 325ml de la línea 12 em 1. 12 beneficios en un solo sistema de cuidado capilar completo. 100% vegano.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","12 beneficios","100% Vegano","Precio especial"], imagen: "/img/lote3/producto22.png", price: "₡10500" },
  { id: 23, nombre: "Kit Frutástica! Uva - Brilho Extremo", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Kit precio especial de la línea Uva con brillo extremo. Incluye shampoo 325ml y acondicionador 325ml. #1 en Brasil.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Extracto de Uva","Brillo extremo","#1 Brasil"], imagen: "/img/lote3/producto23.png", price: "₡10500" },
  { id: 24, nombre: "Kit Bomba de Vitaminas - Crecimiento Espetacular", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Kit precio especial con bomba de vitaminas y ácido hialurónico para crecimiento espectacular. 100% vegano.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Ácido Hialurónico","Vitaminas","100% Vegano"], imagen: "/img/lote3/producto24.png", price: "₡10500" },
  { id: 25, nombre: "Kit Frutástica! Morango - Nutrição e Brilho", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Kit precio especial de la línea Morango con nutrición y brillo. Incluye shampoo 325ml y acondicionador 325ml. #1 en Brasil.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Extracto de Fresa","Nutrición y brillo","#1 Brasil"], imagen: "/img/lote3/producto25.png", price: "₡10500" },
  { id: 26, nombre: "Kit Frutástica! Coco - Nutrição Poderosa", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Kit precio especial de la línea Coco con nutrición poderosa. 100% vegano.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Aceite de Coco","Nutrición poderosa","100% Vegano"], imagen: "/img/lote3/producto26.png", price: "₡10500" },
  { id: 27, nombre: "Kit Frutástica! Melancia - Revitalização de Cachos", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Kit precio especial de la línea Melancia para revitalización de rizos. #1 en Brasil.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Extracto de Sandía","Revitalización de rizos","#1 Brasil"], imagen: "/img/lote3/producto27.png", price: "₡10500" },
  { id: 28, nombre: "Kit Óleo de Argan - Nutrição e Revitalização", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Kit precio especial con aceite de argán. Incluye shampoo sin sal 325ml y acondicionador 325ml. 100% vegano.", caracteristicas: ["Shampoo sin sal 325ml","Acondicionador 325ml","Aceite de Argán","100% Vegano","Precio especial"], imagen: "/img/lote3/producto28.png", price: "₡10500" },
  { id: 29, nombre: "Kit Frutástica! Banana - Reparação Surpreendente", marca: "SKALA (Línea Frutástica!)", categoria: "cabello", descripcion: "Kit precio especial con reparación sorprendente a base de banana. #1 en Brasil.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Extracto de Banana","Reparación sorprendente","#1 Brasil"], imagen: "/img/lote3/producto29.png", price: "₡10500" },
  { id: 30, nombre: "Creme para Pentear Super Desembaraço", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar super desenredante con definición y desembaraço. Para rizados, crespos y difíciles de manejar.", caracteristicas: ["1L","Super desenredante","Definición","Para rizos y crespos"], imagen: "/img/lote3/producto30.png", price: "₡11500" },
  { id: 31, nombre: "Creme para Pentear Super Controle", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar super control con definición y reducción de volumen. Controla el frizz y proporciona definición duradera.", caracteristicas: ["1L","Super control","Reduce volumen","Definición y antifrizz"], imagen: "/img/lote3/producto31.png", price: "₡11500" },
  { id: 32, nombre: "Kit Vitamina C + Colágeno Vegetal - Reparação e Brilho", marca: "SKALA (Línea EXPERT)", categoria: "cabello", descripcion: "Kit con vitamina C y colágeno vegetal. 100% vegano.", caracteristicas: ["Shampoo 325ml","Acondicionador 325ml","Vitamina C","Colágeno Vegetal","100% Vegano"], imagen: "/img/lote3/producto32.png", price: "₡10500" },
  { id: 33, nombre: "Creme para Pentear Super Volumão", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar super volumão con definición y volumen prolongado. Proporciona volumen natural sin pesar.", caracteristicas: ["1L","Super volumen","Definición volumosa","Cabello con cuerpo"], imagen: "/img/lote3/producto33.png", price: "₡11500" },
  { id: 34, nombre: "Creme para Pentear Definição Ultra Volumê", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar en frasco con definición ultra volumen. Antifrizz. Presentación en frasco de 1kg.", caracteristicas: ["1kg","Ultra volumen","Definición","Antifrizz","Nutrición y movimiento"], imagen: "/img/lote3/producto34.png", price: "₡11500" },
  { id: 35, nombre: "Creme para Pentear Super Volumão (Pump)", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar super volumão en presentación con bomba dispensadora. Sistema de 10 beneficios.", caracteristicas: ["1L","Con bomba dispensadora","Super volumen","10 beneficios","Hidratación intensa"], imagen: "/img/lote3/producto35.png", price: "₡11500" },
  { id: 36, nombre: "Creme para Pentear Definição Máxima Liberada", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar con definición máxima liberada. Antifrizz. Presentación en frasco de 1kg.", caracteristicas: ["1kg","Definición máxima","Liberada","Hidratación intensa","Antifrizz"], imagen: "/img/lote3/producto36.png", price: "₡11500" },
  { id: 37, nombre: "Gelatina + Creme para Pentear - Definição Extraordinária", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar con gelatina que proporciona definición extraordinaria. Para todo tipo de rizos.", caracteristicas: ["1kg","Gelatina","Definición extraordinaria","Textura gel-creme","Para todo tipo de rizos"], imagen: "/img/lote4/producto37.png", price: "₡11500" },
  { id: 38, nombre: "S.O.S Hidratação - Máscara Concentrada Aceite de Oliva", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara concentrada con aceite de oliva para tratamiento intensivo. Restaura la fibra capilar desde el interior.", caracteristicas: ["1kg","Aceite de Oliva","Hidratación S.O.S","Máscara concentrada","Restauración intensa"], imagen: "/img/lote4/producto38.png", price: "₡11500" },
  { id: 39, nombre: "S.O.S Hidratação - Máscara Concentrada Óleo de Rícino", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara concentrada con aceite de ricino. Fortalece, estimula el crecimiento y proporciona hidratación intensa.", caracteristicas: ["1kg","Aceite de Ricino","Hidratación S.O.S","Fortalecimiento","Máscara concentrada"], imagen: "/img/lote4/producto39.png", price: "₡11500" },
  { id: 40, nombre: "S.O.S Cachos - Óleo de Rícino e Queratina", marca: "Salon Line", categoria: "cabello", descripcion: "Crema para peinar con aceite de ricino y queratina para reparación y antifrizz.", caracteristicas: ["1kg","Aceite de Ricino","Queratina","Reparación y antifrizz","S.O.S Cachos"], imagen: "/img/lote4/producto40.png", price: "₡11500" },
  { id: 41, nombre: "Hidra Babosa - Queratina e Glicerina Vegetal", marca: "Salon Line", categoria: "cabello", descripcion: "Tratamiento Hidra con aloe vera, queratina y glicerina vegetal. Presentación en botella con dispensador de 1 litro.", caracteristicas: ["1L","Babosa (Aloe Vera)","Queratina","Glicerina Vegetal","Restauración intensa"], imagen: "/img/lote4/producto41.png", price: "₡11500" },
  { id: 42, nombre: "S.O.S Hidratação - Máscara Concentrada Queratina e Colágeno", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara concentrada con queratina y colágeno. Reconstruye la fibra capilar.", caracteristicas: ["1kg","Queratina","Colágeno","Hidratación S.O.S","Máscara concentrada"], imagen: "/img/lote4/producto42.png", price: "₡11500" },
  { id: 43, nombre: "#TodeCacho Ativador de Cachos - Redução Volumosa", marca: "Salon Line", categoria: "cabello", descripcion: "Activador de rizos con reducción volumosa. Ideal para rizos tipo 3 y 4. Presentación de 300ml.", caracteristicas: ["300ml","Activador de rizos","Reducción volumosa","Definición sin frizz"], imagen: "/img/lote4/producto43.png", price: "₡8500" },
  { id: 44, nombre: "S.O.S Cachos - Recarga de Queratina", marca: "Salon Line (Línea S.O.S Cachos)", categoria: "cabello", descripcion: "Activador de rizos con recarga de queratina. Presentación de 500ml.", caracteristicas: ["500ml","Recarga de Queratina","Reparación y brillo","Definición intensa"], imagen: "/img/lote4/producto44.png", price: "₡8500" },
  { id: 45, nombre: "S.O.S Cachos - Ácido Hialurônico", marca: "Salon Line (Línea S.O.S Cachos)", categoria: "cabello", descripcion: "Activador de rizos con ácido hialurónico. Presentación de 500ml.", caracteristicas: ["500ml","Ácido Hialurónico","Hidratación y sellado","Definición duradera"], imagen: "/img/lote4/producto45.png", price: "₡8500" },
  { id: 46, nombre: "S.O.S Cachos - Aceite de Oliva", marca: "Salon Line (Línea S.O.S Cachos)", categoria: "cabello", descripcion: "Activador de rizos con aceite de oliva. Presentación de 500ml.", caracteristicas: ["500ml","Aceite de Oliva","Nutrición y antifrizz","Brillo natural"], imagen: "/img/lote4/producto46.png", price: "₡8500" },
  { id: 47, nombre: "#TodeCacho Ativador de Cachos - Coco", marca: "Salon Line", categoria: "cabello", descripcion: "Activador de rizos con aceite de coco. Presentación de 300ml.", caracteristicas: ["300ml","Aceite de Coco","Definición intensa","Hidratación y brillo"], imagen: "/img/lote4/producto47.png", price: "₡8500" },
  { id: 48, nombre: "Hidra Ativador de Cachos - Hidratação Intensa + Movimento", marca: "Salon Line", categoria: "cabello", descripcion: "Activador de rizos 2 en 1 con D-Pantenol. Presentación de 300ml.", caracteristicas: ["300ml","2 en 1","D-Pantenol","Hidratación intensa","Movimiento natural"], imagen: "/img/lote4/producto48.png", price: "₡8500" },
  { id: 49, nombre: "#TodeCacho Spray Finalizador - Toque de Seda", marca: "Salon Line", categoria: "cabello", descripcion: "Spray finalizador con toque de seda. Brillo intenso y fijación ligera. Presentación de 250ml.", caracteristicas: ["250ml","Spray finalizador","Toque de seda","Brillo y fijación","Antifrizz"], imagen: "/img2/lote5/producto49.png", price: "₡8500" },
  { id: 50, nombre: "Kit Hidra Ceramidas - Shampoo y Acondicionador", marca: "Salon Line", categoria: "cabello", descripcion: "Kit Hidra con ceramidas, D-Pantenol y aceite de jojoba. Shampoo 300ml y acondicionador 300ml.", caracteristicas: ["Shampoo 300ml","Acondicionador 300ml","Ceramidas","D-Pantenol","Aceite de Jojoba"], imagen: "/img2/lote5/producto50.png", price: "₡14000" },
  { id: 51, nombre: "S.O.S Bomba Original - Shampoo Ultra Hidratação Reconstrutora", marca: "Salon Line (Línea S.O.S Bomba)", categoria: "cabello", descripcion: "Shampoo S.O.S Bomba con ultra hidratación reconstructora. 10x más hidratación. Presentación de 300ml.", caracteristicas: ["300ml","10x más hidratación","Ultra hidratación","Reconstructor","Profesional"], imagen: "/img2/lote5/producto51.png", price: "₡8000" },
  { id: 52, nombre: "Meu Lisinho Kids - Creme para Pentear Imaginação e Diversão", marca: "Salon Line (Línea Kids)", categoria: "cabello", descripcion: "Crema para peinar fórmula especial para niños. Fórmula suave y testeada dermatológicamente. Presentación de 300ml.", caracteristicas: ["300ml","Para niños","Desenredante","Sin nudos","Fórmula suave"], imagen: "/img2/lote5/producto52.png", price: "₡8000" },
  { id: 54, nombre: "S.O.S Bomba - Tônico Fortalecedor Crescimento", marca: "Salon Line (Línea S.O.S Bomba)", categoria: "cabello", descripcion: "Tónico fortalecedor para crecimiento capilar. Estimula el crecimiento y reduce la caída. Presentación de 100ml.", caracteristicas: ["100ml","Tónico fortalecedor","Estimula crecimiento","Reduce caída","Aplicación directa"], imagen: "/img2/lote5/producto54.png", price: "₡8000" },
  { id: 55, nombre: "S.O.S Bomba Original - Creme para Pentear Ultra Hidratação", marca: "Salon Line (Línea S.O.S Bomba)", categoria: "cabello", descripcion: "Crema leave-in S.O.S Bomba con ultra hidratación. 13x más hidratación. Presentación de 300ml.", caracteristicas: ["300ml","13x más hidratación","Ultra hidratación","Profesional","Leave-in"], imagen: "/img2/lote5/producto55.png", price: "₡8000" },
  { id: 56, nombre: "S.O.S Bomba - Tônico Fortalecedor Antiqueda", marca: "Salon Line (Línea S.O.S Bomba)", categoria: "cabello", descripcion: "Tónico fortalecedor antiqueda para combatir la caída del cabello. Presentación de 100ml.", caracteristicas: ["100ml","Tónico antiqueda","Fortalece raíz","Estimula folículos","Aplicación directa"], imagen: "/img2/lote5/producto56.png", price: "₡8000" },
  { id: 57, nombre: "Cachos dos Sonhos Multy Maravilhas 3em1", marca: "Salon Line (Línea Cachos dos Sonhos)", categoria: "cabello", descripcion: "Tratamiento 3 en 1 con banho de brilho, nutrición y textura extrema. Presentación de 1kg.", caracteristicas: ["1kg","3 en 1","Banho de brilho","Nutrición","Textura extrema"], imagen: "/img2/lote5/producto57.png", price: "₡14500" },
  { id: 58, nombre: "Cachos dos Sonhos Multy Milagres 3em1", marca: "Salon Line (Línea Cachos dos Sonhos)", categoria: "cabello", descripcion: "Tratamiento 3 en 1 con antiporosidad y maciez extrema. Presentación de 1kg.", caracteristicas: ["1kg","3 en 1","Antiporosidad","Maciez extrema","Multi beneficios"], imagen: "/img2/lote5/producto58.png", price: "₡14500" },
  { id: 59, nombre: "Cachos dos Sonhos Multy Poderosos 3em1", marca: "Salon Line (Línea Cachos dos Sonhos)", categoria: "cabello", descripcion: "Tratamiento 3 en 1 hidratante y brillo luminoso. Sandía. Presentación de 1kg.", caracteristicas: ["1kg","3 en 1","Hidratación poderosa","Brillo luminoso","Sandía"], imagen: "/img2/lote5/producto59.png", price: "₡14500" },
  { id: 60, nombre: "Kit Meu Liso Matizador Loiro - Shampoo y Acondicionador", marca: "Salon Line (Línea Meu Liso)", categoria: "cabello", descripcion: "Kit matizador para cabello rubio. Neutraliza tonos amarillentos. 300ml cada uno.", caracteristicas: ["Shampoo 300ml","Acondicionador 300ml","Matizador","Para rubios","Brillo platinado"], imagen: "/img2/lote5/producto60.png", price: "₡19500" },
  { id: 61, nombre: "#TodeCacho Máscara Matizadora Loira", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara matizadora para cabello rubio. Hidrata, matiza y neutraliza amarillos. Presentación de 500g.", caracteristicas: ["500g","Máscara matizadora","Para rubios","Hidrata y matiza","Neutraliza amarillos"], imagen: "/img2/lote5/producto61.png", price: "₡11500" },
  { id: 62, nombre: "Cachos dos Sonhos Multy Extraordinário 3em1", marca: "Salon Line (Línea Cachos dos Sonhos)", categoria: "cabello", descripcion: "Tratamiento 3 en 1 con reparación intensiva y blindaje antifrizz. Con fresa. Presentación de 1kg.", caracteristicas: ["1kg","3 en 1","Reparación intensiva","Blindaje antifrizz","Fresa"], imagen: "/img2/lote5/producto62.png", price: "₡14500" },
  { id: 63, nombre: "#TodeCacho Máscara Matizadora Vermelha", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara matizadora en tono rojo. Intensifica tonos rojos. Presentación de 500g.", caracteristicas: ["500g","Máscara matizadora","Tono rojo","Hidrata y matiza","Intensifica color"], imagen: "/img2/lote5/producto63.png", price: "₡14500" },
  { id: 64, nombre: "Set Retinol & Ceramides - 4 Piezas", marca: "Nevada", categoria: "skincare", descripcion: "Set completo con Retinol y Ceramides para cuidado facial anti-edad. 4 piezas. El retinol estimula la renovación celular mientras las ceramides fortalecen la barrera cutánea.", caracteristicas: ["4 piezas","Retinol","Ceramides","Anti-edad","Renovación celular"], imagen: "/img2/lote5/producto64.jpg", price: "₡14500" },
  { id: 65, nombre: "Set Hyaluronic Acid - 3 Piezas", marca: "Nevada", categoria: "skincare", descripcion: "Set de Ácido Hialurónico con 3 piezas para hidratación profunda. El ácido hialurónico retiene hasta 1000 veces su peso en agua.", caracteristicas: ["3 piezas","Ácido Hialurónico","Hidratación profunda","Restauración","Anti-arrugas"], imagen: "/img2/lote5/producto65.jpg", price: "₡12500" },
  { id: 66, nombre: "#TodeCacho Máscara Reparação Fortalecedora", marca: "Salon Line", categoria: "cabello", descripcion: "Máscara de reparación fortalecedora. Tratamiento intensivo para rizos dañados. Presentación de 300g.", caracteristicas: ["300g","Reparación","Fortalecedora","Para rizos","Tratamiento intensivo"], imagen: "/img2/lote5/producto66.png", price: "₡8000" },
  { id: 67, nombre: "Set Whitening Skin - 3 Piezas Antimanchas", marca: "Nevada", categoria: "skincare", descripcion: "Set 3 piezas con Arbutina y Niacinamida para tratamiento antimanchas. Aclara y unifica el tono de la piel.", caracteristicas: ["3 piezas","Arbutina","Niacinamida","Antimanchas","Unifica tono"], imagen: "/img2/lote5/producto67.jpg", price: "₡14500" },
  { id: 68, nombre: "Set Aloe Vera - 3 Piezas", marca: "Nevada", categoria: "skincare", descripcion: "Set de Aloe Vera con 3 piezas para suavizar, hidratar y matificar la piel.", caracteristicas: ["3 piezas","Aloe Vera","Hidratante","Matificante","Calma la piel"], imagen: "/img2/lote5/producto68.jpg", price: "₡12500" },
  { id: 69, nombre: "Set Vitamin C - 5 Piezas Anti-Edad", marca: "Nevada", categoria: "skincare", descripcion: "Set de Vitamina C con 5 piezas y Niacinamida. Ilumina, reduce manchas y estimula colágeno.", caracteristicas: ["5 piezas","Vitamina C","Niacinamida","Anti-edad","Iluminador"], imagen: "/img2/lote5/producto69.jpg", price: "₡12500" },
  { id: 70, nombre: "Set Centella Asiática - 4 Piezas", marca: "Nevada", categoria: "skincare", descripcion: "Set de Centella Asiática con 4 piezas para reparación y calma. Incluye banda para cabello.", caracteristicas: ["4 piezas","Centella Asiática","Reparadora","Calma irritaciones","Con banda"], imagen: "/img2/lote6/producto70.jpg", price: "₡10500" },
  { id: 71, nombre: "Mascarilla Facial Aloe Vera - Brillo Natural Hidratante", marca: "Nevada", categoria: "skincare", descripcion: "Mascarilla facial con aloe vera. Brillo natural e hidratación profunda. 30g.", caracteristicas: ["1 unidad","30g","Aloe Vera","Brillo natural","Hidratante"], imagen: "/img2/lote6/producto71.jpg", price: "₡1500" },
  { id: 72, nombre: "Cápsulas Faciales Retinol & Coenzyme Q10 - Renueva y Suaviza", marca: "Nevada", categoria: "skincare", descripcion: "Cápsulas con retinol y coenzima Q10. Renueva y suaviza la piel. 6 cápsulas monodosis.", caracteristicas: ["6 cápsulas","Retinol","Coenzima Q10","Renueva y suaviza","Rostro y cuerpo"], imagen: "/img2/lote6/producto72.jpg", price: "₡1500" },
  { id: 73, nombre: "Cápsulas Faciales Collagen & Hyaluronic Acid - Hidratación y Elasticidad", marca: "Nevada", categoria: "skincare", descripcion: "Cápsulas con colágeno y ácido hialurónico. Hidratación y elasticidad. 6 cápsulas monodosis.", caracteristicas: ["6 cápsulas","Colágeno","Ácido Hialurónico","Hidratación","Elasticidad"], imagen: "/img2/lote6/producto73.jpg", price: "₡1500" },
  { id: 74, nombre: "Mascarillas Contorno de Ojos Whitening Skin - Arbutina y Niacinamida", marca: "Nevada", categoria: "skincare", descripcion: "Mascarillas para contorno de ojos antimanchas con arbutina y niacinamida. 20 pares.", caracteristicas: ["20 pares","6g por par","Arbutina","Niacinamida","Antimanchas"], imagen: "/img2/lote6/producto74.jpg", price: "₡1500" },
  { id: 75, nombre: "Set Serum Nevada - Biotina, Ricino y Romero", marca: "Nevada", categoria: "cabello", descripcion: "Set de 3 sérums capilares: Biotina con Romero, Ricino y Aceite de Ricino con vitaminas.", caracteristicas: ["Set 3 sérums","Biotina","Aceite de Ricino","Romero","Crecimiento capilar"], imagen: "/img2/lote6/producto75.png", price: "₡8000" },
  { id: 76, nombre: "Mascarillas Contorno de Ojos Vitamin C - Vitamina E", marca: "Nevada", categoria: "skincare", descripcion: "Mascarillas para contorno de ojos con vitamina C y vitamina E. 20 pares.", caracteristicas: ["20 pares","6g por par","Vitamina C","Vitamina E","Iluminador"], imagen: "/img2/lote6/producto76.jpg", price: "₡1500" },
  { id: 77, nombre: "Mascarillas Contorno de Ojos Hyaluronic Acid", marca: "Nevada", categoria: "skincare", descripcion: "Mascarillas para contorno de ojos con ácido hialurónico. Hidratación profunda. 20 pares.", caracteristicas: ["20 pares","6g por par","Ácido Hialurónico","Hidratación profunda","Anti-arrugas"], imagen: "/img2/lote6/producto77.jpg", price: "₡1500" },
  { id: 78, nombre: "Stem Cells Facial Tonic - Limpiador Facial de Células Madres", marca: "Nevada", categoria: "skincare", descripcion: "Tónico facial con células madres para limpieza profunda. Efecto matificante. 180ml.", caracteristicas: ["180ml","Células Madres","Limpiador facial","Purifica","Efecto matificante"], imagen: "/img2/lote6/producto78.jpg", price: "₡5500" },
  { id: 79, nombre: "Cápsulas Faciales Aloe Vera & Vitamin E - Suaviza y Revitaliza", marca: "Nevada", categoria: "skincare", descripcion: "Cápsulas con aloe vera y vitamina E. Suaviza y revitaliza. 6 cápsulas monodosis.", caracteristicas: ["6 cápsulas","Aloe Vera","Vitamina E","Suaviza","Revitaliza"], imagen: "/img2/lote6/producto79.jpg", price: "₡1500" },
  { id: 80, nombre: "Facial Mask Naranja con Ácido Hialurónico - Exfoliante Energizante", marca: "Nevada", categoria: "skincare", descripcion: "Mascarilla de naranja con ácido hialurónico. Exfoliante y energizante. 10 unidades.", caracteristicas: ["10 unidades","Naranja","Ácido Hialurónico","Exfoliante","Para piel grasa"], imagen: "/img2/lote6/producto80.jpg", price: "₡1500" },
  { id: 81, nombre: "Mascarillas Contorno de Ojos Aloe Vera", marca: "Nevada", categoria: "skincare", descripcion: "Mascarillas para contorno de ojos con aloe vera. Calma e hidrata. 20 pares.", caracteristicas: ["20 pares","6g por par","Aloe Vera","Calma e hidrata","Anti-inflamatorio"], imagen: "/img2/lote6/producto81.jpg", price: "₡1500" },
  { id: 82, nombre: "Facial Mask Barro Marino con Ácido Hialurónico - Purificante", marca: "Nevada", categoria: "skincare", descripcion: "Mascarilla de barro marino con ácido hialurónico. Purificante. 10 unidades.", caracteristicas: ["10 unidades","Barro Marino","Ácido Hialurónico","Purificante","Para piel grasa"], imagen: "/img2/lote6/producto82.jpg", price: "₡1500" },
  { id: 83, nombre: "Black Mask Whitening Fresa - Aclarador Facial Anti-Edad Toner", marca: "Nevada", categoria: "skincare", descripcion: "Mascarilla negra con extracto de fresa. Whitening anti-edad. 120g.", caracteristicas: ["120g","Extracto de Fresa","Whitening","Anti-edad","Tóner"], imagen: "/img2/lote6/producto83.jpg", price: "₡5500" },
];

async function main() {
  console.log('🌱 Iniciando seed de productos...');

  // Insertar productos usando upsert para evitar duplicados
  for (const producto of productos) {
    await prisma.producto.upsert({
      where: { id: producto.id },
      update: producto,
      create: producto,
    });
  }

  console.log(`✅ ${productos.length} productos insertados/actualizados`);

  // Crear admin
  const bcrypt = require('bcryptjs');
  const hashedPassword = await bcrypt.hash('ramirez1978', 12);

  await prisma.admin.upsert({
    where: { username: 'admin@catalinagonzalez' },
    update: {},
    create: {
      username: 'admin@catalinagonzalez',
      password: hashedPassword,
    },
  });

  console.log('✅ Admin creado: admin@catalinagonzalez');
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('🎉 Seed completado exitosamente');
  })
  .catch(async (e) => {
    console.error('❌ Error en seed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
